export const CONNECT_WALLET = 'CONNECT_WALLET';
export const DISCONNECT_WALLET = 'DISCONNECT_WALLET';
export const SET_PROJECTS = 'SET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const SET_CONTRIBUTIONS = 'SET_CONTRIBUTIONS';
export const SET_WITHDRAW_REQUESTS = 'SET_WITHDRAW_REQUESTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR'; 